### ISSUE TITLE
Generating PDF Error 500 Error

### ISSUE THREAD

**Issue by rocheston** [blacklanternsecurity/writehat#90]
Internal Server Error: /engagements/report/4b564097-d1ab-4dd2-8f04-d9dd2f791843/generatePdf
writehat_1  | Traceback (most recent call last):
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
writehat_1  |     response = get_response(request)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
writehat_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs) 
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
writehat_1  |     response = view_func(request, *args, **kwargs)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/http.py", line 40, in inner
writehat_1  |     return func(request, *args, **kwargs)
writehat_1  |   File "/opt/writehat/./writehat/views.py", line 688, in reportGeneratePdf
writehat_1  |     browser.get(login_uri)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 449, in get
writehat_1  |     self.execute(Command.GET, {"url": url})
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
writehat_1  |     self.error_handler.check_response(response)
writehat_1  |   File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
writehat_1  |     raise exception_class(message, screen, stacktrace)
writehat_1  | selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED
writehat_1  |   (Session info: headless chrome=112.0.5615.165)

**Comment by rocheston** [comment]
I followed the steps you provided for running the application within a Docker container. However, I encountered a 500 error while attempting to generate a PDF report. Additionally, the HTML report appears empty.

**Comment by rocheston** [comment]
Please reply. Thank you.

**Comment by TMDeal** [comment]
Can you try switch to the github-dev branch and seeing if that same error occurs? I have had past experiences where the docker image versions do not like to play well together. The versions for the images should be pinned in the [docker-compose.yml](https://github.com/blacklanternsecurity/writehat/blob/github-dev/docker-compose.yml) in the github-dev branch. If the errors persist after switching branches, can you reply back with the the full logs from docker-compose and I can see if it is another issue entirely.
